const default_colors = Dict{String,Colors.Colorant}("open switch" => colorant"gold",
                                                    "closed switch" => colorant"green",
                                                    "fixed open switch" => colorant"red",
                                                    "fixed closed switch" => colorant"blue",
                                                    "transformer" => colorant"cyan",
                                                    "enabled line" => colorant"black",
                                                    "disabled line" => colorant"orange",
                                                    "energized bus" => colorant"green",
                                                    "energized generator" => colorant"cyan",
                                                    "energized synchronous condenser" => colorant"yellow",
                                                    "enabled generator" => colorant"orange",
                                                    "disabled generator" => colorant"red",
                                                    "unloaded enabled bus" => colorant"darkgrey",
                                                    "unloaded disabled bus" => colorant"grey95",
                                                    "loaded disabled bus" => colorant"gold",
                                                    "loaded enabled bus" => colorant"green3",
                                                    "connector" => colorant"lightgrey")
